### ISSUE TITLE
Periodic write up of CVE vulnerabilities 

### ISSUE THREAD

**Issue by kayiwa** [pulibrary/ops-catchall#1]
Have a periodic write up of [vulnerabilities](https://www.cve.org/) from dependabot pull request from all the active projects on pul.
[dss](https://github.com/pulibrary/DSS/pulls?q=is%3Apr+is%3Aopen+label%3Adependencies)
[figgy](
https://github.com/pulibrary/figgy/pulls?q=is%3Apr+is%3Aopen+label%3Adependencies)
[oawaiver](https://github.com/pulibrary/oawaiver/pulls?q=is%3Apr+is%3Aopen+label%3Adependencies)
[orangelight](https://github.com/pulibrary/orangelight/pulls?q=is%3Apr+is%3Aopen+label%3Adependencies)
[mudd-dbs](https://github.com/pulibrary/mudd-dbs/pulls?q=is%3Apr+is%3Aopen+label%3Adependencies)
[princeton_ansible](https://github.com/pulibrary/princeton_ansible/pulls?q=is%3Apr+is%3Aopen+label%3Adependencies)
[repecwp](https://github.com/pulibrary/repecwp/pulls?q=is%3Apr+is%3Aopen+label%3Adependencies)
[researchdata](https://github.com/pulibrary/researchdata/pulls?q=is%3Apr+is%3Aopen+label%3Adependencies)

**Comment by hackartisan** [comment]
Some of the work here may be an interesting starting point https://github.com/pulibrary/dls-github-labeler/pull/19

**Comment by hackartisan** [comment]
Notes from All-hands session which may be relevant: https://docs.google.com/document/d/1C_VeXTF7-9zImLq6j_0TJWtumSehDuJ4-svgISQRBlo/edit#heading=h.wsvjvyxj8wkh

**Comment by hackartisan** [comment]
Proposal: A ruby script that uses the github API to fetch security / dependabot alerts for all (or a subset of) PUL projects. For each alert, it creates a github issue in https://github.com/PrincetonUniversityLibrary/security/issues, prefixed with some kind of persistent ID. The issue holds a link to the dependabot info, and a list of all affected PUL apps. The issue serves as a central location for developers to discuss approaches to resolution.

The script runs weekly. It doesn't remove existing issues but at each run it ensures the list of affected apps is current.

**Comment by hackartisan** [comment]
close in favor of https://github.com/pulibrary/dependabot-reporter/issues/4
