### ISSUE TITLE
Create a new Dev VM for Upgraded Princeton and Slavery Application

### ISSUE THREAD

**Issue by kevinreiss** [pulibrary/ops-catchall#17]
Create new vm to be used for deployment and testing of the PAS upgrade to craft CMS version 4.x. Upgrade will also include moving the database from MYSQL to POSTGRES.

**Comment by kayiwa** [comment]
Delay from an upgrade of our dev environment (finally unblocked)

**Comment by kayiwa** [comment]
heya @kevinreiss please provide public keys for external devs

**Comment by kayiwa** [comment]
TLS certs for https://github.com/pulibrary/princeton_ansible/pull/3390

**Comment by kevinreiss** [comment]
Think we got one this @kayiwa. I'll close it.
