### ISSUE TITLE
[RDSS] Request to resize disk space for tigerdata-prod2

### ISSUE THREAD

**Issue by jrgriffiniii** [pulibrary/ops-catchall#48]
Currently, members of RDSS have found that the `tigerdata-prod2` server is running critically low on disk space. This is not the case with `tigerdata-prod1`:

```bash
Here is tigerdata-prod1:
/dev/mapper/ubuntu--vg-ubuntu--lv   73G   15G   55G  22% /

And here is tigerdata-prod2:
/dev/mapper/ubuntu--vg-ubuntu--lv   14G   13G  348M  98% /
```

While members of RDSS likely have the authorization to resize logical volumes and disks for these servers, no member has experience with this, and it would be preferred to avoid attempting to undertake this on a production environment server. May we please request assistance and guidance as to how to best proceed?

Thank you very much!

**Comment by acozine** [comment]
Done:
```
tigerdata-prod2% df -h
Filesystem                         Size  Used Avail Use% Mounted on
tmpfs                              791M  1.5M  789M   1% /run
/dev/mapper/ubuntu--vg-ubuntu--lv   73G   13G   57G  19% /
tmpfs                              3.9G     0  3.9G   0% /dev/shm
tmpfs                              5.0M     0  5.0M   0% /run/lock
/dev/sda2                          2.0G  252M  1.6G  14% /boot
tmpfs                              791M  4.0K  791M   1% /run/user/1000
```
