### ISSUE TITLE
Grant Access to VSphere to Beck

### ISSUE THREAD

**Issue by kayiwa** [pulibrary/ops-catchall#63]
Get Access to Beck Davis to the VSphere (both Dev and Prod environment)

Get Beck a remote Windows Machine

Add Beck to Network "Library Systems" Group

Add Beck to Sectigo Group

Get Beck PanOS Firewall Account

**Comment by VickieKarasic** [comment]
All items in this list are now fulfilled, except adding to the Sectigo group(do we have a ticket in with OIT about that @kayiwa?)

**Comment by kayiwa** [comment]
Blocked by OIT waiting for response.
