### ISSUE TITLE
Decommission figgy-edge.lib.princeton.edu

### ISSUE THREAD

**Issue by acozine** [pulibrary/ops-catchall#71]
### What maintenance needs to be done?

Decommission the figgy-edge project.

### Level of urgency
- [ ] High
- [ ] Moderate
- [x] Low

### Why is this maintenance needed?

When we worked on upgrading PostgreSQL for figgy, we created all-new infrastructure for testing the migration. That migration is complete, and we no longer need the infrastructure.

### Acceptance criteria
 - [x] all figgy-edge VMs are deleted (we do not need backups of these VMs)
 - [x] all firewall objects and rules for figgy-edge are deleted (requires ServiceNow ticket)
 - [x] any certificates for figgy-edge.lib.princeton.edu are revoked
 - [ ] any load-balancer configs or other artifacts of this project and deleted/removed

### Implementation notes, if any
According to [ServiceNow](https://princeton.service-now.com/now/nav/ui/classic/params/target/incident.do%3Fsys_id%3Df901c08947ae8a1c06263d54116d43e6%26sysparm_record_target%3Dtask%26sysparm_record_row%3D5%26sysparm_record_rows%3D6%26sysparm_record_list%3Dactive%253Dtrue%255Eassigned_to%253Djavascript%253AgetMyAssignments%2528%2529%255EORDERBYassigned_to), the certificate expires on June 29, 2024.
See also https://github.com/pulibrary/princeton_ansible/pull/4008.

**Comment by Beck-Davis** [comment]
No figgy-edge VMs found in vSphere or objects/rules in Panorama. 
Nothing found load-balancer
Network delete requests submitted for figgy-edge 
Nothing found in princeton_ansible.
