### ISSUE TITLE
decommission nagios-staging1

### ISSUE THREAD

**Issue by kayiwa** [pulibrary/ops-catchall#72]
### Level of urgency
- [ ] High
- [ ] Moderate
- [x] Low

### Why is this maintenance needed?

When we were evaluating monitoring systems we set up a nagios implementation. That evaluation is complete, and we no longer need the vm.

### Acceptance criteria
 - [x] nagios-staging1 vm is deleted
 - [x] nagios-staging1 DNS is deleted
 - [x] nagios-staging alias on the loadbalancer is deleted

**Comment by Beck-Davis** [comment]
@kayiwa Okay to remove [princeton_ansible/playbooks/roles/nginxplus/files/conf/http/nagios-staging.conf](https://github.com/pulibrary/princeton_ansible/blob/7c2aef6cf32bf65e5a30fe7a0aeb625b048247d7/roles/nginxplus/files/conf/http/nagios-staging.conf )

**Comment by kayiwa** [comment]
Go for it and thanks @Beck-Davis

**Comment by Beck-Davis** [comment]
Removed [princeton_ansible/playbooks/roles/nginxplus/files/conf/http/nagios-staging.conf](https://github.com/pulibrary/princeton_ansible/blob/7c2aef6cf32bf65e5a30fe7a0aeb625b048247d7/roles/nginxplus/files/conf/http/nagios-staging.conf)  in https://github.com/pulibrary/princeton_ansible/pull/5153
