### ISSUE TITLE
prometheus-staging1

### ISSUE THREAD

**Issue by kayiwa** [pulibrary/ops-catchall#73]
### Level of urgency
- [ ] High
- [ ] Moderate
- [x] Low

### Why is this maintenance needed?

When we were evaluating monitoring systems we set up a prometheus implementation. That evaluation is complete, and we no longer need the vm.

### Acceptance criteria
 - [x] prometheus-staging1 vm is deleted
 - [x] prometheus-staging1 DNS is deleted
 - [x] nagios-staging alias on the loadbalancer is deleted
 - [ ] we do not need to keep a backup

**Comment by Beck-Davis** [comment]
-prometheus-staging1 vm deleted
-prometheus-staging1 DNS deleted
-prometheus-staging1 alias on loadbalancer deleted
-rules and object for prometheus-staging1 removed from panos

**Comment by Beck-Davis** [comment]
@kayiwa okay to remove [princeton_ansible/playbooks/roles/nginxplus/files/conf/http/prometheus-staging.conf](https://github.com/pulibrary/princeton_ansible/blob/7c2aef6cf32bf65e5a30fe7a0aeb625b048247d7/roles/nginxplus/files/conf/http/prometheus-staging.conf) ?

**Comment by kayiwa** [comment]
Go for it and thanks @Beck-Davis

**Comment by acozine** [comment]
Closed by https://github.com/pulibrary/princeton_ansible/pull/5154
