### ISSUE TITLE
VMs for New Fellows

### ISSUE THREAD

**Issue by VickieKarasic** [pulibrary/ops-catchall#77]
### What maintenance needs to be done?

[Create sandbox](https://github.com/pulibrary/ops-catchall/blob/main/projects/create_new_vm.md) VMs for Denzil (dp1285) and Brionna (bj4103)
[Decommission](https://github.com/pulibrary/pul-it-handbook/blob/main/services/decommissioning.md) Tyler's VM (tw8766)

### Level of urgency
- [ ] High
- [ ] Moderate
- [x] Low

### Why is this maintenance needed?
- Sandbox VMs are needed so that Fellows can participate in the Command Line Curriculum
- Tyler is leaving Princeton, so we will decommission his VM

### Acceptance criteria
 - [x] Create sandbox VM for Denzil on VSphere-prod: sandbox-dp1285.lib.princeton.edu
 - [x] Create sandbox VM for Brionna on VSphere-prod: sandbox-bj4103.lib.princeton.edu
 - [x] Decomission Tyler's sandbox VM (on VSphere-Dev): sandbox-tw8766

### Implementation notes, if any

Brionna has a Windows machine, so ideally, we will test the VM with her before Command Line Curriculum. Resources for this: 

- [https://github.com/microsoft/terminal?tab=readme-ov-file](https://github.com/microsoft/terminal?tab=readme-ov-file)
- [https://github.com/microsoft/terminal](https://github.com/microsoft/terminal)
- [https://hyper.is/](https://hyper.is/)

**Comment by Beck-Davis** [comment]
@kayiwa Denzil is being asked for a password when he tries to ssh into his VM.
